<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/DiskLens.Core/DiskLens.Core.csproj" />
    <ProjectReference Include="../../src/DiskLens.Scanners.Generic/DiskLens.Scanners.Generic.csproj" />
    <ProjectReference Include="../../src/DiskLens.Scanners.Windows/DiskLens.Scanners.Windows.csproj" />
  </ItemGroup>
</Project>
