<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DiskLens.Core/DiskLens.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="DiskLens.Tests" />
  </ItemGroup>
</Project>
