<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../DiskLens.UI/DiskLens.UI.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" />
    <PackageReference Include="Silk.NET.Windowing" />
    <PackageReference Include="Silk.NET.Input" />
    <PackageReference Include="Silk.NET.OpenGL" />
  </ItemGroup>
</Project>
